angular.module('lupo-proto', [
  'ui.router'
  'filters'
  'prompt'
  'statistic'
  'breadcrumb'
  'gettext'
  'notification'
  'translation'
  'angularSpinner'
  'session'
  'crypto'
  'db'
  'fileManager'
  'ng-context-menu'
]).value('dbname', 'lupo-proto')
